from analysis.move.boxes_completed_by_move import boxes_completed_by
from analysis.move.boxes_given_to_opponent import boxes_given_to_opponent
from analysis.move.move_creates_third_edge import creates_third_edge
